import localFont from "next/font/local";
import "./globals.css";
import { DatePickerProvider } from './components/DatePickerContext';

export const metadata = {
  title: "Tick Tick App",
  description: "Generated by create next Tick Tick App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
         <DatePickerProvider>
        {children}
        </DatePickerProvider>
      </body>
    </html>
  );
}
